const SITE_CONFIG = {

  name: 'notlousybook',
  tagline: 'dev from pluto',

  links: {
    github: 'https://github.com/notlousybook',
    discord: 'https://discord.com/users/notlousybook',
    youtube: 'https://www.youtube.com/@notlousybook',
  },

  hero: {
    typewriterTexts: [
      'makes stuff that feels cool',
      'self-taught, from pluto',
      'creative coding & ai',
      '15 and building',
    ],
  },

  projectStats: [
    { target: 41, label: 'repos', icon: 'folder-open' },
    { target: 40, label: 'stars', icon: 'star' },
    { target: 6, label: 'pinned', icon: 'push-pin' },
    { target: '∞', label: 'ideas', icon: 'infinity' },
  ],

  aboutStats: [
    { value: '15', label: 'years old', icon: 'calendar' },
    { value: 'may 13', label: 'birthday', icon: 'calendar' },
    { value: '100%', label: 'self-taught', icon: 'book-open-text' },
  ],

  techStack: [
    { name: 'Python', icon: 'python' },
    { name: 'JavaScript', icon: 'javascript' },
    { name: 'TypeScript', icon: 'typescript' },
    { name: 'Three.js', icon: 'threejs' },
    { name: 'PyWebView', icon: 'pywebview' },
    { name: 'Next.js', icon: 'nextjs' },
    { name: 'Discord.py', icon: 'discordpy' },
    { name: 'ML / AI', icon: 'ml' },
    { name: 'Git', icon: 'git' },
    { name: 'DeepSeek', icon: 'deepseek' },
    { name: 'HTML/CSS', icon: 'htmlcss' },
    { name: 'Creative Coding', icon: 'creative' },
  ],

  footer: {
    tagline: 'dev from pluto',
  },

  testimonials: [
    {
      quote: 'builds stuff that actually works, which is rare. the ai tool fork saved my team months.',
      author: 'github collaborator',
    },
    {
      quote: 'made a discord bot with actual llm brains — half the server thought it was a person.',
      author: 'discord community',
    },
    {
      quote: 'projects are creative and actually useful. rare combo tbh.',
      author: 'fellow dev',
    },
  ],

  collabCards: [
    {
      icon: 'puzzle-piece',
      iconColor: '#1F6C9F',
      title: 'open source',
      desc: 'wanna collab on something? always down to work on cool stuff together',
    },
    {
      icon: 'chat-text',
      iconColor: '#346538',
      title: 'just chatting',
      desc: 'u code? cool. u dont? also cool. if we vibe we vibe — dev or not',
    },
    {
      icon: 'lightning',
      iconColor: '#956400',
      title: '2am ideas',
      desc: 'got a stupid idea at 2am? same. let us actually make it happen',
    },
  ],

  projects: [
    {
      slug: 'pollinations-task-master',
      name: 'pollinations-task-master',
      tagline: 'fork of claude-task-master -- original now supports custom providers',
      description: 'fork of claude-task-master using pollinations.ai as the AI provider for free LLM access',
      longDescription: "a fork of eyaltoledano's claude-task-master that used pollinations.ai as the AI provider so it was 100% free -- no api keys needed. works with cursor ai, cline, and roo code as an mcp server. parse prds, generate tasks, break down projects, track progress -- all powered by ai. heads up: the original claude-task-master now supports custom provider endpoints natively, so you should probably just use that one instead and bring your own provider. this fork was made before that feature existed.",
      stars: 26,
      forks: 7,
      language: 'JavaScript',
      langColor: '#f1e05a',
      icon: 'crosshair',
      url: 'https://github.com/notlousybook/pollinations-task-master',
      accentColor: '#a78bfa',
      features: [
        { icon: 'plant', title: '100% Free AI', description: 'Uses Pollinations.ai -- no private keys, no API costs, completely free LLM access.' },
        { icon: 'link', title: 'Custom Provider Support', description: 'Bring your own OpenAI-compatible endpoint via CUSTOM_BASE / CUSTOM_API_KEY environment variables.' },
        { icon: 'brain', title: 'AI Task Management', description: 'Parse PRDs, generate tasks, break down complex projects into manageable pieces with AI assistance.' },
        { icon: 'arrows-clockwise', title: 'MCP Integration', description: 'Works as an MCP server with Cline, Roo Code, and Cursor AI -- plug right into your workflow.' },
        { icon: 'clipboard-text', title: 'Smart Task Tracking', description: 'Track dependencies, subtasks, and project progress. Never lose context on what needs to be done next.' },
        { icon: 'lightning', title: 'CLI & MCP Dual Mode', description: 'Use via command line for quick tasks or integrate directly into your AI coding workflow as MCP server.' },
      ],
      installCommands: [
        'npm install -g pollinations-taskmaster',
        'task-master init',
      ],
      usageCommands: [
        { command: 'task-master init', description: 'Initialize a new project' },
        { command: 'task-master parse-prd prd.txt', description: 'Parse a PRD and generate tasks' },
        { command: 'task-master list', description: 'List all tasks' },
        { command: 'task-master next', description: 'Show next task to work on' },
        { command: 'task-master generate', description: 'Generate task files' },
        { command: 'task-master models --setup', description: 'Configure AI models' },
      ],
      techStack: ['JavaScript', 'Node.js', 'Shell', 'MCP Protocol', 'Pollinations.ai'],
      tags: ['task-management', 'ai', 'free', 'cursor', 'claude', 'mcp'],
      status: 'Active',
      license: 'MIT with Commons Clause',
    },
    {
      slug: 'deepseek-desktop',
      name: 'DeepSeek-Desktop',
      tagline: 'A desktop wrapper for DeepSeek Chat -- no Electron bloat',
      description: 'Lightweight DeepSeek app built with PyWebView. Zero Electron bloat.',
      longDescription: 'A desktop wrapper for DeepSeek Chat built with PyWebView for zero Electron bloat. Features custom UI polish, time-based greeting system, smooth fade transitions, typing animations, glassmorphic auto-updater notifications, enhanced Markdown rendering with syntax-highlighted code blocks, and a full logging system. Titlebar matches your Windows theme automatically.',
      stars: 7,
      forks: 2,
      language: 'Python',
      langColor: '#3572A5',
      icon: 'robot',
      url: 'https://github.com/notlousybook/DeepSeek-Desktop',
      accentColor: '#7db8ff',
      features: [
        { icon: 'lightning', title: 'Zero Electron Bloat', description: 'Built with PyWebView -- lightweight, minimal memory footprint, fast startup.' },
        { icon: 'pencil-simple', title: 'Custom UI Polish', description: 'Clean interface with smooth transitions and buttery typing animations.' },
        { icon: 'hand-waving', title: 'Dynamic Greetings', description: 'Time-of-day based greetings that rotate through 500+ variations.' },
        { icon: 'arrows-clockwise', title: 'Auto-Updater', description: 'Glassmorphic update notifications with one-click update and restart.' },
        { icon: 'notebook', title: 'Enhanced Markdown', description: 'Full Markdown support, syntax-highlighted code blocks, XSS protection built in.' },
        { icon: 'globe', title: 'Theme-Aware', description: 'Titlebar matches Windows dark/light theme automatically. Force mode via CLI flags.' },
      ],
      installCommands: [
        '# Download latest release from GitHub Releases',
        '# Extract DeepSeekChat-windows.zip',
        '# Run DeepSeekChat.exe',
      ],
      usageCommands: [
        { command: 'DeepSeekChat.exe', description: 'Launch the app' },
        { command: 'Ctrl+Shift+U', description: 'Check for updates manually' },
        { command: 'Ctrl+Shift+L', description: 'Peek at logs' },
        { command: 'DeepSeekChat.exe --dark-titlebar', description: 'Force dark mode' },
        { command: 'DeepSeekChat.exe --light-titlebar', description: 'Force light mode' },
      ],
      techStack: ['Python', 'PyWebView', 'JavaScript', 'Markdown', 'Win32 API'],
      tags: ['desktop-app', 'deepseek', 'ai-client', 'python', 'lightweight', 'pywebview'],
      status: 'Active',
    },
    {
      slug: 'reloadify',
      name: 'reloadify',
      tagline: 'Live-reload for web devs',
      description: 'A lightweight Python CLI tool for live-reloading web content.',
      longDescription: 'A lightweight Python tool that automatically reloads your HTML, CSS, and JavaScript files in the browser while you code. Auto-discovers HTML files in your current directory and subdirectories, watches for changes in real-time, and serves content instantly. Fully configurable with CLI flags for port, directory, and timeout settings.',
      stars: 0,
      forks: 0,
      language: 'Python',
      langColor: '#3572A5',
      icon: 'lightning',
      url: 'https://github.com/notlousybook/reloadify',
      accentColor: '#fbbf24',
      features: [
        { icon: 'rocket', title: 'Blazing Fast', description: 'Instant browser reload the millisecond your file changes.' },
        { icon: 'magnifying-glass', title: 'Ultra-Lightweight', description: 'No heavy dependencies, no bloat. Pure Python performance.' },
        { icon: 'arrows-clockwise', title: 'Live Reloading', description: 'Automatically detects file changes and reloads your browser.' },
        { icon: 'magnifying-glass', title: 'Auto HTML Discovery', description: 'Searches directories for .html files. Prompts if multiple found.' },
        { icon: 'gear-six', title: 'Fully Configurable', description: 'Custom file, directory, port, and auto-shutdown settings via CLI flags.' },
        { icon: 'package', title: 'pip install Ready', description: 'Install globally in one command and use from anywhere.' },
      ],
      installCommands: ['pip install reloadify'],
      usageCommands: [
        { command: 'reloadify', description: 'Serve index.html and watch its folder' },
        { command: 'reloadify my_app/index.html', description: 'Serve a specific HTML file' },
        { command: 'reloadify index.html -d ./src', description: 'Watch a different folder for changes' },
        { command: 'reloadify -p 8080', description: 'Serve on a custom port' },
        { command: 'reloadify -t 3600', description: 'Auto-shutdown after 1 hour' },
      ],
      techStack: ['Python', 'CSS', 'JavaScript', 'HTML'],
      tags: ['cli', 'live-reload', 'web-development', 'python', 'tool'],
      status: 'Stable',
      license: 'MIT',
    },
    {
      slug: 'lousybot',
      name: 'LousyBot',
      tagline: 'Modular Discord bot with LLM smarts',
      description: 'My trusty Discord bot -- doing the things no human should have to.',
      longDescription: "A modular, customizable Discord bot with actual LLM intelligence. Features a flexible provider and model system so you are never locked into one AI service. Easily configurable via .env and plaintext config files. Clean, modular code architecture ready for plugins and custom logic.",
      stars: 0,
      forks: 0,
      language: 'Python',
      langColor: '#3572A5',
      icon: 'robot',
      url: 'https://github.com/notlousybook/LousyBot',
      accentColor: '#5865F2',
      features: [
        { icon: 'lock-key', title: 'Secure Configuration', description: 'Sensitive config files never committed to git. Secrets managed via .env files.' },
        { icon: 'robot', title: 'Flexible AI Integration', description: 'Provider-agnostic LLM system -- no hardcoded API keys. Switch providers anytime.' },
        { icon: 'notebook', title: 'Easy Setup', description: 'Configure with .env and plaintext files -- get running in under 5 minutes.' },
        { icon: 'smiley', title: 'Expressive Style', description: 'Matches the LousyBook personality. Clean interaction design.' },
        { icon: 'wrench', title: 'Plugin Architecture', description: 'Clean, modular code ready for your custom plugins and command extensions.' },
        { icon: 'chat-text', title: 'Smart Mentions', description: 'Context-aware mention handling with intelligent response generation via LLM.' },
      ],
      installCommands: [
        'git clone https://github.com/notlousybook/LousyBot.git',
        'cd LousyBot',
        'pip install -r requirements.txt',
        'cp .env.example .env',
        'python bot.py',
      ],
      usageCommands: [
        { command: 'python bot.py', description: 'Start the bot' },
        { command: '!sync', description: 'Sync slash commands (admin only)' },
      ],
      techStack: ['Python', 'discord.py', 'LLM APIs', 'asyncio'],
      tags: ['discord', 'bot', 'ai', 'python', 'modular'],
      status: 'Alpha',
    },
    {
      slug: 'lousyquiz',
      name: 'LousyQuiz',
      tagline: 'Interactive quiz app for exam survival',
      description: 'An interactive quiz app with AI integration -- made for studying.',
      longDescription: "Made because I forgot everything and needed to study for exams. Built with Bun, Express, and TypeScript for maximum speed. Features JSON file quiz mode where you load your own study materials, progress tracking with a visual progress bar, confetti animations for correct answers, and shuffled questions every time. AI-generated quiz mode is in the works.",
      stars: 0,
      forks: 0,
      language: 'JavaScript',
      langColor: '#f1e05a',
      icon: 'question',
      url: 'https://github.com/notlousybook/LousyQuiz',
      accentColor: '#f472b6',
      features: [
        { icon: 'clipboard-text', title: 'JSON Quiz Mode', description: 'Load and take quizzes from local JSON files -- bring your own study materials.' },
        { icon: 'robot', title: 'AI Quiz Generation', description: 'Generate quizzes on the fly using AI -- planned with multi-provider support.' },
        { icon: 'sparkle', title: 'Animations', description: 'Confetti burst for every correct answer because you deserve it.' },
        { icon: 'chart-bar', title: 'Progress Tracking', description: 'Visual progress bar and real-time score tracking throughout your session.' },
        { icon: 'arrows-clockwise', title: 'Shuffled Content', description: 'Randomized question order and shuffled answer options every time.' },
        { icon: 'gear-six', title: 'Multi-Provider AI', description: 'Supports OpenAI, Gemini, Groq, Mistral, Anthropic, OpenRouter, and custom endpoints.' },
      ],
      installCommands: [
        'git clone https://github.com/notlousybook/LousyQuiz.git',
        'cd LousyQuiz',
        'bun install',
        'bun run index.ts',
      ],
      usageCommands: [
        { command: 'bun run index.ts', description: 'Start the quiz server on port 3000' },
        { command: 'bun run build', description: 'Build to lousyquiz.exe' },
      ],
      techStack: ['TypeScript', 'JavaScript', 'Bun', 'Express', 'HTML/CSS'],
      tags: ['education', 'quiz', 'ai', 'typescript', 'study'],
      status: 'Alpha',
    },
    {
      slug: 'cline-mcp-prompts',
      name: 'Cline-MCP-Prompts',
      tagline: 'Templates for building MCP servers with AI',
      description: 'A set of .clinerules and llms.txt for MCP creation using Cline or Roo Code.',
      longDescription: 'Ready-to-use templates for MCP server creation. Includes .clinerules for AI coding rules and mcp-llms.txt as a comprehensive LLM reference guide. Clone the repo, rename the folder, run the cleanup script, open in VSCode, and prompt Cline or Roo Code to build your MCP server. Created with Gemini 2.0 Pro.',
      stars: 3,
      forks: 1,
      language: 'Shell',
      langColor: '#e8fbf2',
      icon: 'notebook',
      url: 'https://github.com/notlousybook/Cline-MCP-Prompts',
      accentColor: '#34d399',
      features: [
        { icon: 'sparkle', title: '.clinerules Template', description: 'Pre-configured AI coding rules optimized for MCP server development.' },
        { icon: 'user', title: 'LLM Reference Guide', description: 'Comprehensive mcp-llms.txt with everything your AI assistant needs.' },
        { icon: 'pencil-simple', title: 'Cleanup Scripts', description: 'One-command cleanup for Windows, Mac, Linux, and Zsh.' },
        { icon: 'link', title: 'SDK References', description: 'Includes links to Python SDK, TypeScript SDK, and extra documentation.' },
        { icon: 'rocket', title: 'Quick Start', description: 'Clone, rename, clean, open, prompt Cline -- done in under 2 minutes.' },
        { icon: 'link', title: 'Works With', description: 'Compatible with Cline and Roo Code -- two leading AI coding assistants.' },
      ],
      installCommands: [
        'git clone https://github.com/notlousybook/Cline-MCP-Prompts.git',
        '# Rename folder to your server name',
        '# Run clean.ps1 (Win) or clean.sh (Mac/Linux)',
        '# Open in VSCode and prompt Cline/Roo Code',
      ],
      usageCommands: [
        { command: '.\\clean.ps1', description: 'Windows cleanup script' },
        { command: './clean.sh', description: 'Mac/Linux Bash cleanup script' },
        { command: './clean.zsh', description: 'Zsh cleanup script' },
      ],
      techStack: ['Shell', 'PowerShell', 'MCP Protocol', 'VSCode Extensions'],
      tags: ['mcp', 'cline', 'roo-code', 'templates', 'ai-coding'],
      status: 'Stable',
    },
  ],
};
